---
# Desktop applications

- name: Install GUI applications
  become: true
  ansible.builtin.dnf:
    name: "{{ desktop_gui_applications }}"
    state: present

- name: Install GNOME applications/dependencies
  when: gnome_state == 'present'
  become: true
  ansible.builtin.dnf:
    name: "{{ desktop_gnome_applications_dependencies }}"
    state: present

- name: Install KDE applications/dependencies
  when: kde_state == 'present' and desktop_kde_applications_dependencies | length > 0
  become: true
  ansible.builtin.dnf:
    name: "{{ desktop_kde_applications_dependencies }}"
    state: present
