---
base_system_utils:
  - gdisk
  - parted

base_cli_utils:
  - zsh
  - neovim
  - bsdtar
  - yp-tools
  - gnupg2-scdaemon
  - gnupg2-smime

# Host-specific extra packages (override in host_vars)
base_extra_packages: []
