---
desktop_gui_applications:
  - solaar
  - firefox
  - kitty

desktop_gnome_applications_dependencies:
  - gnome-tweaks
  - gnome-extensions-app
  - libgda-sqlite

desktop_kde_applications_dependencies:
  - qutebrowser
  - okular
  - gwenview
